import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebLayout({ children }) {
  return (
   
      <div >
        {children}
      </div>

  );
}
